name: app_bar_with_search_switch
description: An extension for AppBar witch can switch it into search field.
#homepage:
repository: https://github.com/Alexqwesa/app_bar_with_search_switch
#author: Alexqwesa <alexo.veto@gmail.com>

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true


