name: app_bar_with_search_switch
description: An extension for AppBar witch can switch it into search field.
#homepage: https://alexqwesa.github.io/app_bar_with_search_switch/
repository: https://github.com/Alexqwesa/app_bar_with_search_switch
#author: Alexqwesa <alexo.veto@gmail.com>

version: 1.3.9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  speech_to_text: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  lints: any

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true


