# This is a basic workflow to help you get started with Actions

name: example

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    # branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: v2.0(with_stt)
      # - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter
      - name: Install dependencies
        working-directory: ./example
        run: flutter pub get
      - name: Analyze project source
        working-directory: ./example
        run: flutter analyze
      - name: Build example
        working-directory: ./example
        run: flutter build web --release  --base-href /app_bar_with_search_switch/
      - name: Move web to docs
        run: |
          rm -rf docs/
          mv './example/build/web/' 'docs/'
      #- name: Git add  docs
      #  run:  git add -A docs/
      - name: Upload docs
        uses: actions-x/commit@v6
        with:
          # email: me@example.com
          # name: '[Auto] update online example'
          branch: master
          files: docs
          force: true
          repository: https://github.com/Alexqwesa/app_bar_with_search_switch
          token: ${{ secrets.TOKEN }}
          # directory: path/to/different/repo
